version: "3.1"

services:
  user:
    build: .
    restart: always
    ports:
      - 3005:3000
    networks:
      - djarn

  userDb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3309:3306
    volumes:
      - userDb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - djarn

networks:
  djarn:
    external: true

volumes:
  userDb:
