name: test-integration
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build container
        run: docker-compose -f docker-compose.test.yml build
      - name: Test
        run: docker-compose -f docker-compose.test.yml up --exit-code-from user
